Typescript functions and tenderly actions for leveraged tokens
IndexCoop/index-arb-bots pull request #3
Opened 2023-09-15 02:41 UTC by ckoopmann

2023-09-15 07:57 UTC, janndriessen requested changes
LGTM! Some minor findings and comments to clarify.

2023-09-15 07:57 UTC, janndriessen commented on actions/lib/calldata.ts
> +      amountOutMinimum: 0,
This can be ignored or why set to `0`?

2023-09-15 07:57 UTC, janndriessen commented on actions/icreth.ts
> +  const signer = await getSinger(context);
minor: but I'd prefer `getSigner` to be util function and not part of `leveragedTokenArb`

2023-09-15 07:57 UTC, janndriessen commented on test/actions/index.ts
> +import { mint, redeem } from "../../actions/gtceth";
Was this change intended or accidentally pushed?

2023-09-15 07:57 UTC, janndriessen commented on actions/lib/leveragedTokenArb.ts
> +            error: e.toString(),
minor: `toString` might be an issue since `e` is of type `unknown`

2023-09-15 07:57 UTC, janndriessen commented on actions/lib/leveragedTokenArb.ts
> +const tokenParameters = {
Suggesting to add at least `: { [key: string]: any }` as type here or better even define a type for any too to avoid type error on line 87.

2023-09-15 07:57 UTC, janndriessen commented on actions/lib/leveragedTokenArb.ts
> +            optimalResult.flashloanCalldata,
As `optimalResult` could be of two different types it might not have `flashloanCalldata`? At least vscode complains.

2023-09-15 07:57 UTC, janndriessen commented on actions/lib/leveragedTokenArb.ts
> +        predictedBalance: utils.formatEther(optimalResult.predictedBalanceAfter),
`predictedBalanceAfter` may not always be present

2023-09-15 08:09 UTC, FlattestWhite commented on actions/icreth.ts
> +  const signer = await getSinger(context);
gotta get a Singer

2023-09-15 08:09 UTC, FlattestWhite commented on actions/lib/leveragedTokenArb.ts
> +const tokenParameters = {
```
enum LeveragedToken {
   icETH
   icRETH
}

export type TokenParameters = {
        tokenAddress: string;
        swapDataIssue,
        swapDataRedeem
        eiAddress
        unipoolFee
        chainId
}

const tokenParameters: { [key: LeveragedToken]: TokenParameters = {
   LeveragedToken.icETH: {
     ....
   },
   LeveragedToken.icRETH: {
     ...
   }
}
```
So makes adding a new arb bot easy

2023-09-15 08:09 UTC, FlattestWhite commented on hardhat.config.ts
> +        eachLine: (hre) => ({
Damn - what is this hack

2023-09-15 08:09 UTC, FlattestWhite commented on actions/lib/leveragedTokenArb.ts
> +import { Context } from "@tenderly/actions";
small nit: order the absolute imports first, and then the relative imports

2023-09-15 08:09 UTC, FlattestWhite commented on test/leveragedTokens.test.ts
> +    it("buy and redeem icReth", async function () {
Parametize icETH and icRETH?

2023-09-16 05:33 UTC, ckoopmann commented on actions/lib/calldata.ts
> +      amountOutMinimum: 0,
I had errors when setting it to totalWethAmount. Since we are specifying a minimum weth balance to achieve after the arb anyway, we shouldn't need this parameter.

2023-09-16 05:33 UTC, ckoopmann commented on actions/icreth.ts
> +  const signer = await getSinger(context);
Makes sense will move it accordingly.

2023-09-16 05:34 UTC, ckoopmann commented on test/actions/index.ts
> +import { mint, redeem } from "../../actions/gtceth";
accidental. Will undo. (Although the tests should work for both products I guess)

2023-09-16 05:35 UTC, ckoopmann commented on actions/lib/leveragedTokenArb.ts
> +const tokenParameters = {
Good point. Thanks for the type definitions. Will add those

2023-09-16 05:50 UTC, ckoopmann commented on hardhat.config.ts
> +        eachLine: (hre) => ({
No Idea, didn't add this. I just happened to run "Prettier" on it and change the indentation.😅

2023-09-16 05:51 UTC, ckoopmann commented on actions/icreth.ts
> +  const signer = await getSinger(context);
Damn right, reverted back to signer though:
https://github.com/IndexCoop/index-arb-bots/pull/3/commits/53f37702f04681c4f4661d85c8e408147e5e44b3

2023-09-16 05:51 UTC, ckoopmann commented on actions/icreth.ts
> +  const signer = await getSinger(context);
Done: 
https://github.com/IndexCoop/index-arb-bots/pull/3/commits/53f37702f04681c4f4661d85c8e408147e5e44b3

2023-09-16 07:04 UTC, ckoopmann commented on actions/lib/leveragedTokenArb.ts
> +            optimalResult.flashloanCalldata,
Fixed it. Also added the typescript lint / build of the actions directory to the ci, to catch cases like that in the future.

2023-09-16 07:05 UTC, ckoopmann commented on actions/lib/leveragedTokenArb.ts
> +            error: e.toString(),
Good point. Removed it and just print the error object directly

2023-09-16 07:36 UTC, ckoopmann commented on test/leveragedTokens.test.ts
> +    it("buy and redeem icReth", async function () {
icRETH requires a lot of up front simulation / trading to push the prize into arbable territory. So for now I don't think it would improve readability much. But once we have had an arb opportunity on chain similar to iceth we can do it.

2023-09-16 07:36 UTC, ckoopmann commented on actions/lib/leveragedTokenArb.ts
> +const tokenParameters = {
Added a slightly adjusted version of this typing

2023-09-16 07:37 UTC, ckoopmann commented on actions/lib/leveragedTokenArb.ts
> +        predictedBalance: utils.formatEther(optimalResult.predictedBalanceAfter),
Fixed.

2023-09-16 07:38 UTC, ckoopmann commented on actions/lib/leveragedTokenArb.ts
> +import { Context } from "@tenderly/actions";
Removed this dependency from the file since the `getSigner` function was moved to utils.

2023-09-18 07:28 UTC, janndriessen approved these changes
LGTM! As soon as the test passes (again). Might be just something hung up tho?

2023-09-19 02:41 UTC, merged