[DRAFT] CoinDesk trend indicator rebalance bot ($cdETI)
IndexCoop/index-arb-bots pull request #8
Opened 2023-10-04 19:31 UTC by edkim

2023-10-05 09:29 UTC, janndriessen commented on .env.default
> +COINDESK_API=
There is a couple of `no new line at end of file`. Usually, this is just a setting in the editor to fix and it will be automatically done.

2023-10-05 09:31 UTC, janndriessen commented on actions/lib/trendIndexRebalance.ts
> +	}
minor: could return values right away instead of storing in var

2023-10-05 09:32 UTC, janndriessen commented on test/trendIndexRebalance.test.ts
> +});
minor: might be a good thing for utils if it's reused across tests?

2023-10-05 17:23 UTC, edkim commented on .env.default
> +COINDESK_API=
Good tip. Changed it in my VSCode.

2023-10-05 19:42 UTC, edkim commented on actions/lib/trendIndexRebalance.ts
> +    0,
My intention is to always use Flashbots RPC. Is it worth fetching price and enforcing 0.5% slippage here? @ckoopmann @snake-poison

2023-10-05 21:15 UTC, edkim commented on test/trendIndexRebalance.test.ts
> +  // Test if mock server returns expected values
This feels like too much code for what I'm trying to do. I'd like to come back to this when my brain is fresh.

2023-10-06 05:00 UTC, ckoopmann requested changes
Good work. 
Went a bit more strict / nit picky then normal here, because you asked for it😅

Also ofc, please fix CI before consider merging and probably merge in cbbeth branch first and then update this one.

2023-10-06 05:32 UTC, janndriessen commented on .github/workflows/test.yml
> +  COINDESK_API: ${{ secrets.COINDESK_API }}
Just to make sure, you don't need `TREND_INDEX_REBALANCER_PRIVATE_KEY` or `COINDESK_API` here?

2023-10-06 05:47 UTC, janndriessen commented on test/actions/cdeti.ts
> +
I think the test run time may require it. It's the recommended way from the docs: https://docs.tenderly.co/web3-actions/references/local-development-and-testing. Feel free to try with just using jest tho.

2023-10-06 09:10 UTC, janndriessen commented on actions/lib/trendIndexRebalance.ts
> +        sendQuantity = wethComponentUnits.div(2);
Does it mean selling half of the WETH? To be 50% WETH 50% USDC in the neutral strategy.

2023-10-06 09:11 UTC, janndriessen commented on actions/lib/trendIndexRebalance.ts
> +        sendQuantity = wethComponentUnits.div(2);
As suggested above by Christian it's probably good to either add a few comments or break up the function into multiple smaller _config_/_strategy_ functions

2023-10-06 16:57 UTC, edkim commented on tenderly.yaml
> +            blocks: 1200
The CoinDesk API only gets updated once per day, so this should be fine. 

Separately, Allan requested that any rebalance transactions be done at a random time within 24 hours of the trend score being updated. I haven't thought of a good way to do that yet. Any ideas @FlattestWhite?

2023-10-06 17:04 UTC, edkim commented on test/actions/cdeti.ts
> +
Tenderly docs recommend we run the action from within our Jest tests, but I don't think that adds much value since we can just call tryArb or tryRebalance [sic] directly. 

It does provide an easy way to trigger the action from CLI, which came in handy while developing.

2023-10-11 03:15 UTC, edkim commented on test/trendIndexRebalance.test.ts
> +  // Test if mock server returns expected values
I ended up hoisting the Coingecko API call out of the `tryTrendIndexRebalance` function and removing the mock api tests.

2023-10-11 03:53 UTC, edkim commented on package.json
> +    "cdeti-rebalance-test": "hardhat test test/trendIndexRebalance.test.ts",
Removed!

2023-10-11 04:42 UTC, edkim commented on test/actions/cdeti.ts
> +  blockEvent.blockNumber = 18220964;
I deleted these blockEvent lines since I don't know if they're needed. Let's see if Tenderly complains.

2023-10-11 17:04 UTC, edkim commented on test/trendIndexRebalance.test.ts
> +    describe("and trend token is 100% usdc", function () {
I've tried to make it more clear that before certain tests, we run `tryTrendIndexRebalance()` with a hardcoded trend score, to trade into the token composition we want to test against.

Perhaps a better way is to avoid using `tryTrendIndexRebalance()` in our tests, and instead use helper functions to achieve the fork state we want.

2023-10-11 17:06 UTC, edkim commented on .github/workflows/test.yml
> +  COINDESK_API: ${{ secrets.COINDESK_API }}
Added, thanks!

2023-10-12 19:03 UTC, edkim commented on test/trendIndexRebalance.test.ts
> +        expect(wethBalanceAfter).to.be.gt(wethBalanceBefore);
I think it's enough. We could add a price oracle check but don't think it's worth it.

2023-10-12 19:22 UTC, edkim commented on actions/lib/utils.ts
> +    const provider = new providers.JsonRpcProvider(rpcUrl, 1);
Note that this replaces an environment secret for JSON-RPC URL with a hardcoded Flashbots RPC URL. This also means that the icreth and iceth web3actions will also now use Flashbots.

2023-10-13 07:41 UTC, ckoopmann commented on actions/lib/trendIndexRebalance.ts
> +  switch (trendScore) {
Yes, definetely more readable this way👏

2023-10-13 07:42 UTC, ckoopmann commented on test/trendIndexRebalance.test.ts
> +        expect(wethBalanceAfter).to.be.gt(wethBalanceBefore);
Okay. Up to you.

2023-10-13 07:44 UTC, ckoopmann commented on actions/lib/utils.ts
> +    const provider = new providers.JsonRpcProvider(rpcUrl, 1);
I think it is better to keep it in the secret and just set the secret value to the flashbots rpc. That way we are able to change the rpc if we want to by just updating the secret. (if we keep it like this we need to adjust the whole code and redeploy the actions).

2023-10-13 07:45 UTC, ckoopmann commented on actions/lib/utils.ts
> +    const provider = new providers.JsonRpcProvider(rpcUrl, 1);
Also the flashbots rpc is pretty prone to rate limiting which I had a lot of issues with on my own arb bots.
We probably want to configure it such that we only use flashbots for the final transaction and not all of the simulation calls before

2023-10-13 07:46 UTC, ckoopmann commented on actions/lib/utils.ts
> +    const provider = new providers.JsonRpcProvider(rpcUrl, 1);
It is also slower than alchemy and does not give us the logging. Another reason why we would want to use it only where we need to.

2023-10-13 08:03 UTC, ckoopmann requested changes
Mostly just added additional comments / answers to previously raised nitpicks. All of those are optional though, will leave it up to you in the end. 

One point I would definetely change though is not to use the Flashbots RPC everywhere. This  url is much slower when running the different simulations etc. and rate limits pretty aggressively so it should only be used where it is actually needed. (which is when submitting transactions that are subject to potential frontrunning). I had my personal arb bots repeatedly hang / fail to execute due to this.

Also we should fix flaky test first before merging. Lmk if you need my support there. (it is one of the tests that I added that is flaking after all😅)

Overall great work despite my nit picking here and there🙏

2023-10-13 08:03 UTC, ckoopmann commented on test/trendIndexRebalance.test.ts
> +  // Test if mock server returns expected values
That means the api fetching / trend score calculation is not tested at all anymore though, right ?

2023-10-13 15:18 UTC, edkim commented on actions/lib/utils.ts
> +    const provider = new providers.JsonRpcProvider(rpcUrl, 1);
Ah good thing you know from experience. I'll split it back out as a separate Secret. I think it's good to be able to change the RPC without re-deploying...but I don't love that there's no record of what the secret has been changed to/from, which could make it harder to debug later.

2023-10-13 15:23 UTC, edkim commented on test/trendIndexRebalance.test.ts
> +  // Test if mock server returns expected values
Correct about no longer testing the API fetching. Is there a reason we'd want to test the fetching through an Axios mock? 

If the live CoinDesk API is down or they change the response format, mock tests wouldn't catch it.

2023-10-16 02:41 UTC, ckoopmann commented on test/trendIndexRebalance.test.ts
> +  // Test if mock server returns expected values
The part of the code you'd be testing would be the handing of the response not the coindesk api. I.e. that your code correctly calculates the trend score from the api response.

I'm not sure how much logic there is for that and how complex it is though, so I'd leave it up to you if you want to that part of your code

2023-10-16 02:42 UTC, ckoopmann commented on actions/lib/utils.ts
> +    const provider = new providers.JsonRpcProvider(rpcUrl, 1);
You could include the rpc url in the logs for debugging.

2023-10-18 20:32 UTC, edkim commented
@ckoopmann I've updated the PR with
- Using Flashbots RPC only for executing rebalance Tx
- Deleted separate `test/actions/cdeti.ts` test file, and combined the runtime test with the other hardhat tests, as you suggested.
- Added Discord notifications, which uses Tenderly storage so that we can change alert subscribers easily.

2023-10-19 04:07 UTC, ckoopmann approved these changes
Great Work! Thanks for the patience and diligence!
LGTM + LFG !!!

2023-10-19 11:42 UTC, merged

2023-10-23 12:42 UTC, pblivin0x commented on actions/lib/trendIndexRebalance.ts
> +async function getUniV3SwapData(
potential to add slippage protection here?